### ISSUE TITLE
Issue with flask, causing http3_server.py to fail

### ISSUE THREAD

**Issue by Karthikdasari0423** [aiortc/aioquic#324]
root@ubuntu:~# python /root/aioquic/examples/http3_server.py --certificate /root/aioquic/tests/ssl_cert.pem --private-key /root/aioquic/tests/ssl_key.pem -v
Traceback (most recent call last):
  File "/root/aioquic/examples/http3_server.py", line 561, in <module>
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/aioquic/examples/demo.py", line 9, in <module>
    import httpbin
  File "/usr/local/lib/python3.8/dist-packages/httpbin/__init__.py", line 3, in <module>
    from .core import *
  File "/usr/local/lib/python3.8/dist-packages/httpbin/core.py", line 18, in <module>
    from flask import Flask, Response, request, render_template, redirect, jsonify as flask_jsonify, make_response, url_for, abort
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/usr/local/lib/python3.8/dist-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

**Comment by Karthikdasari0423** [comment]
use pip install -U 'flask<2.2.0'  to make http3_server.py work again

**Comment by Karthikdasari0423** [comment]
ERROR: flask 2.2.2 has requirement Werkzeug>=2.2.2, but you'll have werkzeug 2.0.3 which is incompatible.

**Comment by jlaine** [comment]
Yeah this situation sucks, I hope that httpbin update their code soon. What version of flask do we need to keep things working with werkzeug<2.1 ?

**Comment by Karthikdasari0423** [comment]
In Ubuntu 20 version pip3 install -U 'flask<2.2.0'  worked fine for me. and i believe Flask 2.1.3 is good.
